services:
  - type: web
    name: dhansetu-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ML_API_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BHASHINI_USER_ID
        sync: false
      - key: BHASHINI_UDYAT_API_KEY
        sync: false
      - key: BHASHINI_INFERENCE_API_KEY
        sync: false
      - key: BHASHINI_PIPELINE_ID
        sync: false

  - type: web
    name: dhansetu-ml
    runtime: python
    rootDir: ml_model
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
